spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${EV_POSTGRES_DB}
    username: ${EV_POSTGRES_USERNAME}
    password: ${EV_POSTGRES_PASSWORD}
  redis:
    host: localhost
    port: 6379
properties:
  telegram:
    name: ${EV_BOT_NAME}
    token: ${EV_BOT_TOKEN}