name: Deploy
  
on:  
  push:  
    branches: [ master ]
  
jobs:  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
      - uses: actions/checkout@v3  
  
      - name: Set up JDK 11
        uses: actions/setup-java@v3.0.0
        with:  
          java-version: '11'  
          distribution: 'temurin'  
  
      - name: Assembly  
        run: ./gradlew telegram-bot:assemble
  
      - name: Deploy to remote  
        uses: garygrossgarten/github-action-scp@release  
        with:  
          local: telegram-bot/build/libs/telegram-bot.jar
          remote: /home/evfunnytest/builds/evfunnytest.jar  
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
